apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: retry-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: retry-container
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              if [ -f /data/succeeded ]; then
                echo "Already succeeded on previous retry"
                exit 0
              fi
              
              if [ -f /data/attempted ]; then
                echo "Retrying and now succeeding..."
                touch /data/succeeded
                exit 0
              else
                echo "First attempt, simulating failure..."
                touch /data/attempted
                exit 1
          volumeMounts:
            - name: retry-volume
              mountPath: /data
      volumes:
        - name: retry-volume
          persistentVolumeClaim:
            claimName: retry-pvc
